### ISSUE TITLE
David - end the game when the time has run out RPC stuff

### ISSUE THREAD

**Issue by laurensWe** [matsmulder/MinorProject#26]
- [x] Game over screen when time runs out
- [x] Show correct game over screen for both teams
  - [x] Get pickup count for both teams
  - [x] Get kills for both teams
- [x] Return to main menu after game over screen

**Comment by hkLolgast** [comment]
@veselkad

**Comment by hkLolgast** [comment]
- [x] Game over screen when time runs out
- [ ] Show correct game over screen for both teams (based on kills?)
- [ ] Return to main menu after game over screen
