### ISSUE TITLE
Hugo - sample code for parsing JSON to server.js

### ISSUE THREAD

**Issue by laurensWe** [matsmulder/MinorProject#27]
//*******************\* c# http request (send to server)

var httpWebRequest = (HttpWebRequest)WebRequest.Create("http://url");
httpWebRequest.ContentType = "text/json";
httpWebRequest.Method = "POST";

using (var streamWriter = new StreamWriter(httpWebRequest.GetRequestStream()))
{
    string json = "{\"user\":\"test\"," +
                  "\"password\":\"bla\"}";

```
streamWriter.Write(json);
streamWriter.Flush();
streamWriter.Close();
```

}

// ***************\* c # http response (get from server)

var httpResponse = (HttpWebResponse)httpWebRequest.GetResponse();
using (var streamReader = new StreamReader(httpResponse.GetResponseStream()))
{
    var result = streamReader.ReadToEnd();
}

**Comment by hkLolgast** [comment]
@HugoReijm
